<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add New Offer</name>
   <tag></tag>
   <elementGuidId>077c5c99-8313-4254-b813-e5716ed19854</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.new-boffer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_basket_offers']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Add New Offer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bb6f34d6-65b0-4d02-b005-5cae5bb86dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>new-boffer</value>
      <webElementGuid>0cacb421-58b0-47d0-8a9a-e881bdc31d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add New Offer</value>
      <webElementGuid>3ea378b7-6aa7-413a-a0e3-dcfd962c3c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_basket_offers&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content ng-untouched ng-pristine ng-valid&quot;]/a[@class=&quot;new-boffer&quot;]</value>
      <webElementGuid>d90129ba-7c8e-42d4-b8ee-a5d36736c41a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_basket_offers']/div/div/div/div/a</value>
      <webElementGuid>1e964dd9-68cb-41e0-b0bb-e3858599d0f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add New Offer')]</value>
      <webElementGuid>e33799b5-d663-42ae-9bf9-9a7f15c57dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acquisition Offer Definitions'])[1]/following::a[1]</value>
      <webElementGuid>5fccfea5-ccce-4363-9ab2-d85ad9c5d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[3]/following::a[1]</value>
      <webElementGuid>cc6cc5d0-1cc6-4c71-b410-8e49fb356406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[3]/preceding::a[1]</value>
      <webElementGuid>9959aeae-a5d5-4d88-805f-c018a55ffd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add New Offer']/parent::*</value>
      <webElementGuid>50f92483-ed7f-49b2-9264-d5e4fb6482a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>faa1617f-ec43-4855-8c2e-ede5505ba2e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Add New Offer' or . = 'Add New Offer')]</value>
      <webElementGuid>925b5527-909a-431c-9a30-c7dba56dba56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
