<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Issue Credit_1</name>
   <tag></tag>
   <elementGuidId>829c94b7-2094-492e-a806-8624b11f95bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.continue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal_issue_credit >> internal:role=button[name=&quot;Issue Credit&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>67a95539-6211-41a4-8c8c-7ed7ce2d903d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8b47398d-8bba-4290-8370-02e1a6227262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>continue</value>
      <webElementGuid>3503673f-0f76-4d6b-8368-28549a7a69bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Issue Credit</value>
      <webElementGuid>30f2060d-68c0-4226-af9a-bf7c6378b19f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_issue_credit&quot;)/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog modal-issue&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;modal-footer clearfix&quot;]/button[@class=&quot;continue&quot;]</value>
      <webElementGuid>58a80754-6eae-4c5f-9ef4-d8858b07e396</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>da5fcbe0-cf36-4873-9afb-f6c2cf586f83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_issue_credit']/div/div/div/form/div[2]/button</value>
      <webElementGuid>0163ab47-5cfa-4f45-8def-1096377e61be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Volker Hauf'])[2]/following::button[1]</value>
      <webElementGuid>ba031498-c6e5-4216-995c-ccae9b2d383e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Issue Credit'])[1]/following::button[1]</value>
      <webElementGuid>bfa74f13-bd86-4fe1-9870-c1af71e30775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>3515c229-32b1-440b-8c3d-0a51a96963a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Issue Credit' or . = 'Issue Credit')]</value>
      <webElementGuid>10328799-331d-4bef-8935-dc83b742301a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
