<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Create Offer_clearfix</name>
   <tag></tag>
   <elementGuidId>2cb0289c-d6dd-405d-9337-cc1befa2661e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.clearfix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='breadcrumb']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.clearfix >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49db351d-30e6-47e7-b344-a084a34e961d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearfix</value>
      <webElementGuid>cdd32c0b-aaae-4d50-ae70-eec04083c02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;breadcrumb&quot;)/div[@class=&quot;clearfix&quot;]</value>
      <webElementGuid>fc8b6ebe-8d4b-4a2b-9323-f9a5e0dd1381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='breadcrumb']/div[4]</value>
      <webElementGuid>675c52fc-a757-405d-836c-82361237881e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>0ab2af53-0c99-4ace-aa3f-04af7d2d6198</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
