<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address__58_login</name>
   <tag></tag>
   <elementGuidId>2dd74381-f3ab-4f58-98c5-21aa18a55a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_58_login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_58_login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c8b5733-5460-476d-84d2-5c872ba95ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field clearable</value>
      <webElementGuid>2d2bf13b-215a-4387-8623-87f170fb2642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>3a8e7a68-552b-4c33-9951-c35fae47bda1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>9df8d186-d285-41a2-96b5-4330e0c28b13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>1e542328-d428-4873-9b0d-85f3762d0d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_58_login&quot;)</value>
      <webElementGuid>317b029c-1cc0-4a50-a23b-ed0ff85914e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_58_login']</value>
      <webElementGuid>df39756c-00e9-48e6-bf5e-8673561f3ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_58_fm']/fieldset/div/div/input</value>
      <webElementGuid>de7b914d-c28d-4f0a-806c-62a3cfb33fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>9d25269c-6e9c-4648-afcf-ffdb379b898d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_58_login' and @name = '_58_login' and @type = 'email']</value>
      <webElementGuid>6bc97c5c-e42e-4263-bfec-68218265ae08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737956617098_177']/input</value>
      <webElementGuid>0842dd30-5a38-4bbb-b0f5-07e86075f37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737716879232_177']/input</value>
      <webElementGuid>f1b89408-5754-4479-8229-97a2ee8c300f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737356966124_177']/input</value>
      <webElementGuid>8f83f4ce-b1e0-402c-9e02-bbd7449013e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737356435218_177']/input</value>
      <webElementGuid>a7c139a6-dd08-4e14-a5c8-9d72e6b76cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737351973981_177']/input</value>
      <webElementGuid>c849476f-ce3a-4d2c-8ca6-fe0318e014a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737347053468_177']/input</value>
      <webElementGuid>f82c6879-9d52-48c2-92e4-ed03b77bbf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737346784464_177']/input</value>
      <webElementGuid>70900f1e-0fd4-451e-9cbd-08b570911fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737344773029_177']/input</value>
      <webElementGuid>599daa44-ed59-4a38-9d8f-c4543f0b1508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737025173314_177']/input</value>
      <webElementGuid>00a2185b-b09f-4a6b-9de7-bc6163b527b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736940584357_177']/input</value>
      <webElementGuid>7cfca168-d6e2-4629-82bb-029a22f8f556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736844710446_177']/input</value>
      <webElementGuid>b893dd19-9eae-4acf-84ff-6974ff05e5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736837900615_177']/input</value>
      <webElementGuid>627d39bc-b126-4ed8-b8d6-3913c0f32860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
