<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address__58_login</name>
   <tag></tag>
   <elementGuidId>2dd74381-f3ab-4f58-98c5-21aa18a55a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_58_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_58_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab931920-cc38-45fd-a922-0e6af257ca77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field clearable</value>
      <webElementGuid>9a449c37-0821-4c7f-9dfc-d6a88de895f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>53cb3fb4-ffca-47e7-b563-0bcd1dfbeb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>2404e9fc-2c80-4dae-b48a-0001ee5bcb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>5a427c1d-c21e-43ed-94e5-0b4c087fff1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_58_login&quot;)</value>
      <webElementGuid>f15bb640-79da-4cf3-9632-63e453acdd46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_58_login']</value>
      <webElementGuid>0f974545-145b-4b76-9543-3b4bb6fcc5f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='_58_fm']/fieldset/div/div/input</value>
      <webElementGuid>99d9933c-8184-490c-bdaf-476e9991dce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>cff06bbe-71bd-4ae2-9ba0-8397d0257048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_58_login' and @name = '_58_login' and @type = 'email']</value>
      <webElementGuid>f67e1468-6c35-483c-9402-f8f0c84ffbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737356966124_177']/input</value>
      <webElementGuid>8f83f4ce-b1e0-402c-9e02-bbd7449013e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737356435218_177']/input</value>
      <webElementGuid>a7c139a6-dd08-4e14-a5c8-9d72e6b76cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737351973981_177']/input</value>
      <webElementGuid>c849476f-ce3a-4d2c-8ca6-fe0318e014a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737347053468_177']/input</value>
      <webElementGuid>f82c6879-9d52-48c2-92e4-ed03b77bbf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737346784464_177']/input</value>
      <webElementGuid>70900f1e-0fd4-451e-9cbd-08b570911fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737344773029_177']/input</value>
      <webElementGuid>599daa44-ed59-4a38-9d8f-c4543f0b1508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1737025173314_177']/input</value>
      <webElementGuid>00a2185b-b09f-4a6b-9de7-bc6163b527b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736940584357_177']/input</value>
      <webElementGuid>7cfca168-d6e2-4629-82bb-029a22f8f556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736844710446_177']/input</value>
      <webElementGuid>b893dd19-9eae-4acf-84ff-6974ff05e5c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736837900615_177']/input</value>
      <webElementGuid>627d39bc-b126-4ed8-b8d6-3913c0f32860</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
