<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Redeemable Through_redemptionEndDate</name>
   <tag></tag>
   <elementGuidId>e7b11f73-5290-4a0b-9749-a0ac118f4daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#redemptionEndDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='redemptionEndDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Redeemable Through&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>57627641-34e9-4b49-840b-a5b9beb297d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>cfd0324c-bb3a-4c80-9824-750d68f78448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c72b4daf-547d-4b82-853f-ec9540adb25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>redemptionEndDate</value>
      <webElementGuid>5f1b5554-d775-46e3-96ce-f104c10e0a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>188ad335-0a02-4e04-8ae6-98042af5ed0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>redemptionEndDate</value>
      <webElementGuid>39dd5795-bda4-4141-8017-818bc6511bfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker date hasDatepicker ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>6b22d766-c743-4a57-87bf-a83f76948a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>redemptionEndDate</value>
      <webElementGuid>eb8bdcff-6385-4870-9deb-1e69ca49199a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;redemptionEndDate&quot;)</value>
      <webElementGuid>3a55aa39-1e16-4134-a168-46ea9aa8f221</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='redemptionEndDate']</value>
      <webElementGuid>e4cda6a2-a4b7-44f7-bb63-4eff3adf0f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>6063715d-7ca0-4679-9ef2-e1b5cae5034c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'redemptionEndDate' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>82b47157-4263-43d7-ada3-17bc6db6925f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
