<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_ng-untouched ng-pristine ng-valid</name>
   <tag></tag>
   <elementGuidId>300e35ca-184d-473e-8dd7-fa4552e9b9ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.first_info_city > input.ng-untouched.ng-pristine.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^City$/ >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12002f1d-521b-4dd7-8272-24297d1e698d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8af2eb35-a254-46e7-94b2-a383043e5e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>90f3cb03-7eda-495c-a03d-a6ef11c8713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>b5fea159-caef-418d-bff7-62e7dbb3aa2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>9bc0b61e-0d06-4705-9e9d-bae7deaea25a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8a3dadc1-b634-424f-84a3-30b67fe00e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-site-layout[1]/div[@class=&quot;container&quot;]/div[@class=&quot;portlet-body&quot;]/app-edit-customer[1]/div[@class=&quot;supportApp&quot;]/div[@class=&quot;tab&quot;]/section[@class=&quot;offers_list_personal&quot;]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;personal_info_form&quot;]/div[@class=&quot;information&quot;]/div[@class=&quot;first_info&quot;]/div[@class=&quot;first_info_city&quot;]/input[@class=&quot;ng-untouched ng-pristine ng-valid&quot;]</value>
      <webElementGuid>d8ac376d-5107-4bdd-900e-d4afb15e4c10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[7]</value>
      <webElementGuid>5daa4d95-9147-4e96-b994-40fa1dd6c4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>44302e3c-e7dc-4a6e-9fac-a0d321a6d210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>e819c1f4-02f4-42d2-bfec-cd2b94205738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
