<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_End_endDate</name>
   <tag></tag>
   <elementGuidId>1b22d793-3bff-4803-b440-c85aa1716d66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#endDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='endDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;End *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>764e09dd-8c48-4db7-ad8c-49f9fe2f631c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>228ec0b7-86ff-4537-9c3c-d5a742de2c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1087eea8-c772-4e5a-8f7a-7b20e61e2b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>f0b3f5de-7c21-4bc5-9168-f70289d3a933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>mm/dd/yyyy</value>
      <webElementGuid>becd8fb3-889c-4d4a-9a8a-031020387c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>5e4f5a21-5415-4771-8d01-bd36c165b0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datepicker date hasDatepicker ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bdb654a9-9922-4ce5-963e-2bda9960237c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>endDate</value>
      <webElementGuid>617f036b-e671-48d2-8cce-801c3366485d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;endDate&quot;)</value>
      <webElementGuid>2641b586-c592-44cb-8691-2dcd7db9e418</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='endDate']</value>
      <webElementGuid>c56be78a-8b98-4fd0-aeea-8c694fc45968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>bf6d8b55-cb76-4f14-a8fa-6422ac38d797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'endDate' and @placeholder = 'mm/dd/yyyy']</value>
      <webElementGuid>6e8cc304-35cb-40a4-a879-8fe52cc70a70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
