<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Welcome_LowCost_1</name>
   <tag></tag>
   <elementGuidId>6b71404a-c1e2-44b6-8809-a804f6b169af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[title=&quot;Welcome_LowCost_1&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_select_segment']/div/div/div/div/div/div[2]/perfect-scrollbar/div/div/ul/li/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome_LowCost_1&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6ee77867-998c-4d78-8c40-b3b3f9cbcd98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>aud_145156</value>
      <webElementGuid>19b1c213-a4bd-47e1-b752-2e2e61d6bcd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome_LowCost_1</value>
      <webElementGuid>d02bc68d-abc3-40f1-a6dd-4c28949d387f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome_LowCost_1</value>
      <webElementGuid>e78dc51d-5a1c-4ad4-bef7-131b01c02d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_select_segment&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;left-sec sec&quot;]/div[@class=&quot;scrollbox&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;item-list&quot;]/li[1]/label[1]</value>
      <webElementGuid>9c20fe7d-c62e-4cd0-bb75-48a411dcd0d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_select_segment']/div/div/div/div/div/div[2]/perfect-scrollbar/div/div/ul/li/label</value>
      <webElementGuid>24ce5462-eb64-423f-b465-fd6a8b92598b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Audiences'])[1]/following::label[1]</value>
      <webElementGuid>bde7a400-e009-442d-870c-7839f14ac808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::label[1]</value>
      <webElementGuid>d8e40100-f459-460a-bba7-abbcf04e7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome_LowCost_2'])[1]/preceding::label[1]</value>
      <webElementGuid>65b7c0e8-3c53-41b9-be22-8c03b8431303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome_LowCost_3'])[1]/preceding::label[2]</value>
      <webElementGuid>5054fadf-077b-460f-8810-b72600db4ce0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome_LowCost_1']/parent::*</value>
      <webElementGuid>cce4b8e9-ac01-40ef-8650-8dda0f420c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/label</value>
      <webElementGuid>0136c7a8-c938-40f8-beb1-dc6215c1c616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Welcome_LowCost_1' and (text() = 'Welcome_LowCost_1' or . = 'Welcome_LowCost_1')]</value>
      <webElementGuid>75dd5864-e005-4d0a-94e4-475a56c2c63a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
