<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Welcome_LowCost_2</name>
   <tag></tag>
   <elementGuidId>de0e8923-72db-4a2f-be53-c9de63649342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label[title=&quot;Welcome_LowCost_2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_select_segment']/div/div/div/div/div/div[2]/perfect-scrollbar/div/div/ul/li[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Welcome_LowCost_2&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a3b60c12-9d73-4d0d-8fe9-91ce8b2e39ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>aud_145174</value>
      <webElementGuid>c66cd872-3f32-44bf-b9b8-539cdc1bee9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Welcome_LowCost_2</value>
      <webElementGuid>c0ad2321-3ce3-483c-8cd9-53c6986fd55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome_LowCost_2</value>
      <webElementGuid>efcff2c4-d18d-4fd8-ac9a-475864a6745b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_select_segment&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;left-sec sec&quot;]/div[@class=&quot;scrollbox&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps ps--active-y&quot;]/div[@class=&quot;ps-content&quot;]/ul[@class=&quot;item-list&quot;]/li[2]/label[1]</value>
      <webElementGuid>522cd874-7c51-4309-a2e9-56edfb9cbe0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_select_segment']/div/div/div/div/div/div[2]/perfect-scrollbar/div/div/ul/li[2]/label</value>
      <webElementGuid>bb64b02b-5890-484c-9eea-651642a3fe74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome_LowCost_1'])[1]/following::label[1]</value>
      <webElementGuid>cf4724a3-646a-47c9-80a9-a57c817c9bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Audiences'])[1]/following::label[2]</value>
      <webElementGuid>b88d185a-7347-4f3f-94b8-4a6a129e89da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome_LowCost_3'])[1]/preceding::label[1]</value>
      <webElementGuid>c6b59258-2eb7-4261-8b9a-5e91d742306f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome_LowCost_4'])[1]/preceding::label[2]</value>
      <webElementGuid>92f860fa-c4f0-4473-93e5-c1de13cd7daa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome_LowCost_2']/parent::*</value>
      <webElementGuid>34ca8c0d-6133-4feb-8f73-3bff634e33e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/label</value>
      <webElementGuid>a9b103dc-2e97-45c0-8c96-46a14af31bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Welcome_LowCost_2' and (text() = 'Welcome_LowCost_2' or . = 'Welcome_LowCost_2')]</value>
      <webElementGuid>95171846-e2eb-46e0-b16b-780b38a045eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
