<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Produce</name>
   <tag></tag>
   <elementGuidId>a54534aa-1713-4184-a31f-3bb9809ab035</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='select-manu-options']/li[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#select-manu-options > li:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Produce&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>36853f44-e01e-437f-ac53-1bfadc9295d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>730fffdb-6fcc-4abe-9586-c12f70efafa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Produce</value>
      <webElementGuid>b721004a-ef55-4c04-bb4b-d4d40dc7f36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;select-manu-options&quot;)/li[2]</value>
      <webElementGuid>1feafc60-5787-4556-81cc-a8a51fc708ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='select-manu-options']/li[2]</value>
      <webElementGuid>3838f90a-bfcd-4c8f-87a7-12495dc8300a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Root Categories'])[2]/following::li[1]</value>
      <webElementGuid>461218e6-7196-447e-8694-f6bcad421748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Root Categories'])[1]/following::li[2]</value>
      <webElementGuid>09738a29-742e-473a-a94a-11e7aaa2c512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dairy, Eggs &amp; Cheese'])[1]/preceding::li[1]</value>
      <webElementGuid>cb012cb6-32ec-4ae8-9130-c91659f45573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packaged Foods'])[1]/preceding::li[2]</value>
      <webElementGuid>9c1cc252-2a33-4284-b6fc-e2ac858f0119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Produce']/parent::*</value>
      <webElementGuid>34971346-2e3f-4156-b74a-5a4827842082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div/ul/li[2]</value>
      <webElementGuid>21426455-63c7-41bd-b2c6-23009bb428cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Produce' or . = 'Produce')]</value>
      <webElementGuid>14a12829-35e4-45f4-bbd3-dc3356f231e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookies, Snacks &amp; Candy'])[2]/following::li[1]</value>
      <webElementGuid>b94447d0-ad18-415a-b253-f539100f6f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Root Category'])[1]/following::li[1]</value>
      <webElementGuid>04456b0c-a547-49fd-826d-7da54b22eb5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dairy, Eggs &amp; Cheese'])[2]/preceding::li[1]</value>
      <webElementGuid>22e46c2b-23ce-416c-9da9-a9cceebe7707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packaged Foods'])[2]/preceding::li[2]</value>
      <webElementGuid>039c7a85-f393-452b-94ab-ec9a8c3783f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li</value>
      <webElementGuid>1234fb95-9b4a-41b2-9eca-6edea5a6325e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
