<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Phone</name>
   <tag></tag>
   <elementGuidId>39952874-4d1f-4fd2-876e-54d31bcbdf84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li[value=&quot;conType.key&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@value='conType.key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#modal_note >> internal:text=&quot;Phone&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>98de5bdf-8196-447f-92f5-0835843b49a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>conType.key</value>
      <webElementGuid>71583afc-e49c-4220-ba81-911c22142681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>2fdd5695-4339-4aff-8cd8-90404e27265f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_note&quot;)/div[@class=&quot;modal&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/form[@class=&quot;ng-pristine ng-invalid ng-touched&quot;]/div[@class=&quot;modal-body clearfix&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;form-group col6&quot;]/div[@class=&quot;select-container&quot;]/ul[@class=&quot;select-menu&quot;]/li[1]</value>
      <webElementGuid>4f15f5de-694e-47dd-b573-ef64c97d6d3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@value='conType.key']</value>
      <webElementGuid>734f9e29-e206-4028-a4d7-f181295f1b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_note']/div/div/div/form/div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>6a820e6e-4c33-4335-b1c8-6dc4c75bb517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact type'])[1]/following::li[1]</value>
      <webElementGuid>cb8eb307-b64e-4952-8279-28e49169daec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date / Time'])[1]/following::li[1]</value>
      <webElementGuid>a55690c4-5a6d-4a70-b829-a88c94b3a5a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[3]/preceding::li[1]</value>
      <webElementGuid>c8d14039-fe5f-4cb2-9dc0-a6db719ad139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outbound'])[2]/preceding::li[2]</value>
      <webElementGuid>b58fc7b9-5620-48ab-bda5-b4c6824f040d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/ul/li</value>
      <webElementGuid>2b84065e-3bd5-41e3-a607-48640286baa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Phone' or . = 'Phone')]</value>
      <webElementGuid>5d23450d-7615-4671-b2a2-40201a460cfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
