<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Select</name>
   <tag></tag>
   <elementGuidId>61fbdd5d-c415-4de7-a1c6-67af2a376253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.select-container.dd.basketTemp > span.select-menu-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal_basket_offers']/div/div/div/div/div/perfect-scrollbar/div/div/div/div[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Select&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3f541301-c7f3-4b36-aeac-74e8ab9c2d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select-menu-toggle</value>
      <webElementGuid>dc86cefc-52e6-41c3-87d7-c4328d8bf2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select</value>
      <webElementGuid>889fada1-ca7e-485e-8941-3c4a44c9d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal_basket_offers&quot;)/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;modal-content ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;scrollbox&quot;]/perfect-scrollbar[1]/div[@class=&quot;ps&quot;]/div[@class=&quot;ps-content&quot;]/div[@class=&quot;form-group boffer-elem ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;select-container dd basketTemp&quot;]/span[@class=&quot;select-menu-toggle&quot;]</value>
      <webElementGuid>dad38ad7-e3c4-4b25-9bb0-828f971be3b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal_basket_offers']/div/div/div/div/div/perfect-scrollbar/div/div/div/div[3]/span</value>
      <webElementGuid>3ef090fb-42c2-468a-b84e-3fee1fd7fc9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='in'])[1]/following::span[1]</value>
      <webElementGuid>2655e790-0828-4d5f-bb31-e27714a41047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$'])[4]/following::span[2]</value>
      <webElementGuid>a3e5f62f-3cfe-4674-879f-0f930b50fab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GROCERY'])[1]/preceding::span[1]</value>
      <webElementGuid>ce14eb00-90ed-4f19-831a-51e136dd82a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEAT'])[1]/preceding::span[1]</value>
      <webElementGuid>1c264610-7018-414a-93d2-e0571727391c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Select']/parent::*</value>
      <webElementGuid>ce79cded-24f8-45eb-9366-724df940d63c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//perfect-scrollbar/div/div/div/div[3]/span</value>
      <webElementGuid>de5f4ee0-5fcf-4fa4-8347-4dc24c37e1c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Select' or . = 'Select')]</value>
      <webElementGuid>d1aea2b1-a652-4fcc-a31e-52fd1926ee16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
