<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>//ul[@id=&quot;select-manu-options&quot;]</description>
   <name>ul_SelectOptions</name>
   <tag></tag>
   <elementGuidId>300df36a-eeea-43e5-abd9-a9918d09d1b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id=&quot;select-manu-options&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
