<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Offers</name>
   <tag></tag>
   <elementGuidId>4ded8cf0-1aba-4620-82d1-2f95eb28b92b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_menu']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Offers&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55f0f605-254a-41a6-a5c2-0b82f162fa4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/group/campaigna/listing</value>
      <webElementGuid>0e76c893-ed66-4e63-b8f5-01c5f19bb3af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Offers</value>
      <webElementGuid>b106dd72-8485-4344-bc38-6e75a86c92c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_menu&quot;)/ul[@class=&quot;main_menu&quot;]/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>521a72cf-780d-4532-b89e-71f95f325759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_menu']/ul/li[2]/a</value>
      <webElementGuid>475db80b-5421-4d4f-911b-4d3bed64799d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Offers')]</value>
      <webElementGuid>b7aaaa7e-965c-49f6-bdb1-22c02e8b984b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campaigns'])[1]/preceding::a[1]</value>
      <webElementGuid>13225310-1de0-4501-8c23-e3365538a2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audiences'])[1]/preceding::a[2]</value>
      <webElementGuid>8c06c76b-9ba2-4281-85a6-3c40d9cee9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Offers']/parent::*</value>
      <webElementGuid>057945a3-a088-4fef-9141-2caad15195c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/group/campaigna/listing')]</value>
      <webElementGuid>1be15f79-c833-47b0-abc1-b80c6017ab9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>c310defe-13b6-4eb9-87b6-8a4af110393c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/group/campaigna/listing' and (text() = 'Offers' or . = 'Offers')]</value>
      <webElementGuid>0d656b88-41a7-4ebe-b390-84d6018c1e54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
