<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address__58_login</name>
   <tag></tag>
   <elementGuidId>f82c7516-1cc2-4efa-99ff-9f434624bdea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_58_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_58_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10b98dcb-7c64-4c85-ba35-340a8be95682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field clearable</value>
      <webElementGuid>2470f5ca-dff5-45a2-a262-889995151865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>eebcfbb3-ee89-45b1-993c-d408b4137053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>2be9cbd6-f612-4e8b-b2b2-5f14866032ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>568549c2-f1a0-43e7-9adc-6bb67bc371a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_58_login&quot;)</value>
      <webElementGuid>65a36719-3a01-4178-bb40-b797db3ab629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_58_login']</value>
      <webElementGuid>ea51b31e-4ac1-4822-9bc8-bcc13f0da495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736843763188_177']/input</value>
      <webElementGuid>c7638d96-ae3b-4710-aed7-3ba95fe6262e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>16e8acde-9734-4651-83f5-dc0928c58865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_58_login' and @name = '_58_login' and @type = 'email']</value>
      <webElementGuid>20090eca-6db7-486b-86ed-bd8959e77c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
