<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Priyanka Gupta</name>
   <tag></tag>
   <elementGuidId>9e6ae1e3-3883-4d82-ba82-c91ff52bcd52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='user_menu']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Priyanka Gupta&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>18728609-b00e-42f3-bb30-5c3fb9a61d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5f6c29d1-e433-40f0-87e5-388bb77fa1cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle</value>
      <webElementGuid>24f51cc6-2945-4862-8167-1d6816249491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Priyanka Gupta</value>
      <webElementGuid>00529f7e-8088-4867-9ae9-1813a3987298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;user_menu&quot;)/ul[@class=&quot;user_menu&quot;]/li[@class=&quot;user dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]</value>
      <webElementGuid>d14e52ed-f762-47b6-9f14-ec7c139a6efb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='user_menu']/ul/li/a</value>
      <webElementGuid>fad76348-8d15-4e5f-af77-d34b08cb229c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Priyanka Gupta')]</value>
      <webElementGuid>afa76147-3921-4e4d-9c62-a88cab104c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalog'])[1]/following::a[1]</value>
      <webElementGuid>5f371b56-4a3a-4f4e-99ad-6250d4e5218a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Support'])[1]/following::a[2]</value>
      <webElementGuid>b8d9ff30-2b05-44ac-a07d-84a52df5d736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/preceding::a[1]</value>
      <webElementGuid>e9a31913-b7db-41c6-a9ec-df321807c96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::a[2]</value>
      <webElementGuid>d99e8509-125a-4353-8865-bd88b4b75fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Priyanka Gupta']/parent::*</value>
      <webElementGuid>299ac7bf-5632-4140-b1d9-4f2a6b46b360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>b14b6714-7b83-4561-bd4a-50ca2b0d000f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li/a</value>
      <webElementGuid>c31ef943-1dce-4f94-8af0-74a8f92d5f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Priyanka Gupta' or . = 'Priyanka Gupta')]</value>
      <webElementGuid>e016fc4d-6d5a-451e-bf35-145774ac4c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
