<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address__58_login</name>
   <tag></tag>
   <elementGuidId>58bcdc02-46d2-4dbc-913d-6877e28afaf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_58_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_58_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email Address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75360a4f-710f-4efb-b0b5-3bfc6d4aafee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field clearable</value>
      <webElementGuid>fdaebdb7-e6bb-4765-8c0b-5b30aeb570d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>665c795a-3b3a-4033-8173-7164603c30d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_58_login</value>
      <webElementGuid>3fdfd34f-f0d2-4adb-b9e7-861d66ab5545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>4e129772-4254-4932-b834-1a71e1a7b10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_58_login&quot;)</value>
      <webElementGuid>ecea30ef-df2f-498c-aefa-502724b5126c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_58_login']</value>
      <webElementGuid>5fb07f14-c5fc-4759-a2ba-1d1c43dad96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='yui_patched_v3_11_0_1_1736844047254_177']/input</value>
      <webElementGuid>043247c7-b49e-4ad6-895c-1c1c2274d629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>765585a0-40bd-482b-bfaf-1522c58e07cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_58_login' and @name = '_58_login' and @type = 'email']</value>
      <webElementGuid>28ba052d-05aa-47a4-97a3-dc54cc268942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
